package leeyuri.mobile.bunjang_mok_aos.src.main.following

import leeyuri.mobile.bunjang_mok_aos.R
import leeyuri.mobile.bunjang_mok_aos.config.BaseFragment
import leeyuri.mobile.bunjang_mok_aos.databinding.FragmentFollowingRecommendBinding

class FollowingRecommendFragment : BaseFragment<FragmentFollowingRecommendBinding>(FragmentFollowingRecommendBinding::bind, R.layout.fragment_following_recommend)